[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "mysql", "nodejs", "yarn"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "yarn install --frozen-lockfile",
  "yarn build"
]
