[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "mysql", "nodejs", "yarn"]

[phases.build]
cmds = [
  "composer clear-cache",
  "composer install --no-dev --optimize-autoloader --prefer-dist",
  "ls -al /app/vendor",
  "yarn install --frozen-lockfile",
  "yarn build"
]

[phases.deploy]
cmds = [
  "php bin/console cache:clear --env=dev", 
  "php bin/console doctrine:migrations:migrate --no-interaction"
]