[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "mysql", "nodejs", "yarn"]

[phases.build]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --optimize-autoloader",
  "yarn install --frozen-lockfile",
  "yarn build"
]
